batchsize : 256
per : 0.95
fra : 0.1
scaling_factor : 2.0
random : 161311
radius : 0.6
lr : 0.0005
ptfolder : "/cluster/project/igc/kpaul/datasets/FullTrainingSet/"
ptfile : "full_ds_XXX.pt"
epochs : 50
modelid : 0
hidden : 64
hidden_token : 128
num_solvents : 42
name : 'ProductionRun'
clip : 1.0
limit : 1000
num_random_samples : 5
compile : False
dropout : 0.1
seed : 161311
scheduler : "Exponential50"
use_tmpdir : False
dataloader_prefetch_factor : 2
dataloader_num_workers : 2
dataloader_pinned_memory : False
logging_frequency : 20
training_solvents : "../Simulation/solvents.yml"
