# Setup deposition external test set
python run_deposit_database.py -s 0 -e 2 -t test -h5 "Calculated_data/Externalt_test_set_additional_Chloroform/ClC(Cl)Cl_small_molecules_n_50_id_XXX_seed_161311.hdf5" -nc 1 -d solvent_chloroform
python run_deposit_database.py -s 0 -e 1 -t test -h5 "Calculated_data/Externalt_test_set_additional_Methanol/CO_small_molecules_n_50_id_XXX_seed_161312.hdf5" -nc 1 -d solvent_methanol
python run_deposit_database.py -s 0 -e 1 -t test -h5 "Calculated_data/Externalt_test_set_additional_DMSO/CS(=O)C_small_molecules_n_50_id_XXX_seed_161313.hdf5" -nc 1 -d solvent_dmso
python run_deposit_database.py -s 0 -e 1 -t test -h5 "Calculated_data/Externalt_test_set_additional_DMPU/O=C1N(C)CCCN1C_small_molecules_n_50_id_XXX_seed_161314.hdf5" -nc 1 -d solvent_dmpu
python run_deposit_database.py -s 0 -e 1 -t test -h5 "Calculated_data/Externalt_test_set_additional_Diethylether/CCOCC_small_molecules_n_50_id_XXX_seed_161315.hdf5" -nc 1 -d solvent_diethylether
python run_deposit_database.py -s 0 -e 1 -t test -h5 "Calculated_data/Externalt_test_set_additional_Ethanol/OCC_small_molecules_n_50_id_XXX_seed_161316.hdf5" -nc 1 -d solvent_ethanol
python run_deposit_database.py -s 0 -e 1 -t test -h5 "Calculated_data/Externalt_test_set_additional_DMF/CN(C)C=O_small_molecules_n_50_id_XXX_seed_161317.hdf5" -nc 1 -d solvent_dmf
python run_deposit_database.py -s 0 -e 1 -t test -h5 "Calculated_data/Externalt_test_set_additional_DCM/ClCCl_small_molecules_n_50_id_XXX_seed_161318.hdf5" -nc 1 -d solvent_dcm
python run_deposit_database.py -s 0 -e 1 -t test -h5 "Calculated_data/Externalt_test_set_additional_Toluol/Cc1ccccc1_small_molecules_n_50_id_XXX_seed_161319.hdf5" -nc 1 -d solvent_toluol
python run_deposit_database.py -s 0 -e 1 -t test -h5 "Calculated_data/Externalt_test_set_additional_Benzol/c1ccccc1_small_molecules_n_50_id_XXX_seed_161320.hdf5" -nc 1 -d solvent_benzol
python run_deposit_database.py -s 0 -e 1 -t test -h5 "Calculated_data/Externalt_test_set_additional_Hexan/CCCCCC_small_molecules_n_50_id_XXX_seed_161321.hdf5" -nc 1 -d solvent_hexan
python run_deposit_database.py -s 0 -e 1 -t test -h5 "Calculated_data/Externalt_test_set_additional_acetonitrile/CC#N_small_molecules_n_50_id_XXX_seed_161322.hdf5" -nc 1 -d solvent_acetonitrile
python run_deposit_database.py -s 0 -e 2 -t test -h5 "Calculated_data/Externalt_test_set_additional_acetone/CC(=O)C_small_molecules_n_50_id_XXX_seed_161323.hdf5" -nc 1 -d solvent_acetone
python run_deposit_database.py -s 0 -e 2 -t test -h5 "Calculated_data/Externalt_test_set_additional_aceticacid/CC(O)=O_small_molecules_n_50_id_XXX_seed_161324.hdf5" -nc 1 -d solvent_aceticacid
python run_deposit_database.py -s 0 -e 2 -t test -h5 "Calculated_data/Externalt_test_set_additional_14dioxane/O1CCOCC1_small_molecules_n_50_id_XXX_seed_161325.hdf5" -nc 1 -d solvent_14dioxane
python run_deposit_database.py -s 0 -e 1 -t test -h5 "Calculated_data/Externalt_test_set_additional_nitrobenzol/c1ccc(cc1)[N+](=O)[O-]_small_molecules_n_50_id_XXX_seed_161326.hdf5" -nc 1 -d solvent_nitrobenzol
python run_deposit_database.py -s 0 -e 1 -t test -h5 "Calculated_data/Externalt_test_set_additional_HMPA/O=P(N(C)C)(N(C)C)N(C)C_small_molecules_n_50_id_XXX_seed_161327.hdf5" -nc 1 -d solvent_hmpa
python run_deposit_database.py -s 0 -e 2 -t test -h5 "Calculated_data/Externalt_test_set_additional_MTBE/O(C(C)(C)C)C_small_molecules_n_50_id_XXX_seed_161328.hdf5" -nc 1 -d solvent_mtbe
python run_deposit_database.py -s 0 -e 1 -t test -h5 "Calculated_data/Externalt_test_set_additional_IPA/CC(O)C_small_molecules_n_50_id_XXX_seed_161329.hdf5" -nc 1 -d solvent_ipa
python run_deposit_database.py -s 0 -e 2 -t test -h5 "Calculated_data/Externalt_test_set_additional_Hexafluorobenzene/Fc1c(F)c(F)c(F)c(F)c1F_small_molecules_n_50_id_XXX_seed_161330.hdf5" -nc 1 -d solvent_hexafluorobenzene
python run_deposit_database.py -s 0 -e 2 -t test -h5 "Calculated_data/Externalt_test_set_additional_pyridine/c1ccncc1_small_molecules_n_50_id_XXX_seed_161331.hdf5" -nc 1 -d solvent_pyridine
python run_deposit_database.py -s 0 -e 1 -t test -h5 "Calculated_data/Externalt_test_set_additional_THF/C1CCOC1_small_molecules_n_50_id_XXX_seed_161332.hdf5" -nc 1 -d solvent_thf
python run_deposit_database.py -s 0 -e 1 -t test -h5 "Calculated_data/Externalt_test_set_additional_Ethylacetate/O=C(OCC)C_small_molecules_n_50_id_XXX_seed_161333.hdf5" -nc 1 -d solvent_ethylacetate
python run_deposit_database.py -s 0 -e 1 -t test -h5 "Calculated_data/Externalt_test_set_additional_Sulfolane/C1CCS(=O)(=O)C1_small_molecules_n_50_id_XXX_seed_161334.hdf5" -nc 1 -d solvent_sulfolane
python run_deposit_database.py -s 0 -e 1 -t test -h5 "Calculated_data/Externalt_test_set_additional_nitromethane/C[N+](=O)[O-]_small_molecules_n_50_id_XXX_seed_161335.hdf5" -nc 1 -d solvent_nitromethane
python run_deposit_database.py -s 0 -e 1 -t test -h5 "Calculated_data/Externalt_test_set_additional_Butylformate/CC(C)(C)OC=O_small_molecules_n_50_id_XXX_seed_161336.hdf5" -nc 1 -d solvent_butylformate
python run_deposit_database.py -s 0 -e 1 -t test -h5 "Calculated_data/Externalt_test_set_additional_NMP/CN1CCCC1=O_small_molecules_n_50_id_XXX_seed_161337.hdf5" -nc 1 -d solvent_nmp
python run_deposit_database.py -s 0 -e 1 -t test -h5 "Calculated_data/Externalt_test_set_additional_Octanol/CCCCCCCCO_small_molecules_n_50_id_XXX_seed_161338.hdf5" -nc 1 -d solvent_octanol
python run_deposit_database.py -s 0 -e 2 -t test -h5 "Calculated_data/Externalt_test_set_additional_cyclohexane/C1CCCCC1_small_molecules_n_50_id_XXX_seed_161339.hdf5" -nc 1 -d solvent_cyclohexane
python run_deposit_database.py -s 0 -e 1 -t test -h5 "Calculated_data/Externalt_test_set_additional_glycerin/OCC(O)CO_small_molecules_n_50_id_XXX_seed_161340.hdf5" -nc 1 -d solvent_glycerin
python run_deposit_database.py -s 0 -e 1 -t test -h5 "Calculated_data/Externalt_test_set_additional_carbontetrachloride/ClC(Cl)(Cl)Cl_small_molecules_n_50_id_XXX_seed_161341.hdf5" -nc 1 -d solvent_carbontetrachloride
python run_deposit_database.py -s 0 -e 13 -t test -h5 "Calculated_data/Externalt_test_set_additional_DME/COCCOC_small_molecules_n_50_id_XXX_seed_161342.hdf5" -nc 1 -d solvent_dme
python run_deposit_database.py -s 0 -e 3 -t test -h5 "Calculated_data/Externalt_test_set_additional_2Nitropropane/CC(C)[N+](=O)[O-]_small_molecules_n_50_id_XXX_seed_161343.hdf5" -nc 1 -d solvent_2nitropropane
python run_deposit_database.py -s 0 -e 2 -t test -h5 "Calculated_data/Externalt_test_set_additional_Trifluorotoluene/C1=CC=C(C=C1)C(F)(F)F_small_molecules_n_50_id_XXX_seed_161344.hdf5" -nc 1 -d solvent_trifluorotoluene
python run_deposit_database.py -s 0 -e 1 -t test -h5 "Calculated_data/Externalt_test_set_additional_hexafluroacetone/FC(F)(F)C(=O)C(F)(F)F_small_molecules_n_50_id_XXX_seed_161345.hdf5" -nc 1 -d solvent_hexafluroacetone
python run_deposit_database.py -s 0 -e 1 -t test -h5 "Calculated_data/Externalt_test_set_additional_Propionitrile/CCC#N_small_molecules_n_50_id_XXX_seed_161346.hdf5" -nc 1 -d solvent_propionitrile
python run_deposit_database.py -s 0 -e 1 -t test -h5 "Calculated_data/Externalt_test_set_additional_Benzonitrile/N#Cc1ccccc1_small_molecules_n_50_id_XXX_seed_161347.hdf5" -nc 1 -d solvent_benzonitrile
python run_deposit_database.py -s 0 -e 2 -t test -h5 "Calculated_data/Externalt_test_set_additional_oxylol/CC1=C(C)C=CC=C1_small_molecules_n_50_id_XXX_seed_161348.hdf5" -nc 1 -d solvent_oxylol
