# Setup additional external test set

mkdir -p /cluster/project/igc/kpaul/Additional_external_test_set/Chloroform_starting_coordinates
mkdir -p additional_external_caches/CACHE_Chloroform_external_test_set/
mkdir -p Calculated_data/Externalt_test_set_additional_Chloroform
job0=$(sbatch --parsable --array=0-1 -n 4 --time=24:00:00 --tmp=1000 --mem-per-cpu=4000 -o Calculated_data/slurm_log/run_generation_external_test_additional_Chloroform_starting_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "ClC(Cl)Cl" -r 161311 -f generation_smiles/missing_testset_smiles/missing_smiles_Chloroform.npy --startonly --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/Chloroform_starting_coordinates/ --cachelocation additional_external_caches/CACHE_Chloroform_external_test_set/ --oneonly -sl Calculated_data/Externalt_test_set_additional_Chloroform/')
sbatch --dependency=afterany:$job0 --array=0-1 -n 4 --time=24:00:00 --tmp=5000 --mem-per-cpu=4000 --gpus=1 -o Calculated_data/Externalt_test_set_additional_Chloroform/slurm_log/run_generation_Chloroform_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "ClC(Cl)Cl" -r 161311 -f generation_smiles/missing_testset_smiles/missing_smiles_Chloroform.npy -nf 1 --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/Chloroform_starting_coordinates/ -sl Calculated_data/Externalt_test_set_additional_Chloroform/ --cachelocation additional_external_caches/CACHE_Chloroform_external_test_set/ --oneonly'

mkdir -p /cluster/project/igc/kpaul/Additional_external_test_set/Methanol_starting_coordinates
mkdir -p additional_external_caches/CACHE_Methanol_external_test_set/
mkdir -p Calculated_data/Externalt_test_set_additional_Methanol
job1=$(sbatch --parsable --array=0-0 -n 4 --time=24:00:00 --tmp=1000 --mem-per-cpu=4000 -o Calculated_data/slurm_log/run_generation_external_test_additional_Methanol_starting_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "CO" -r 161312 -f generation_smiles/missing_testset_smiles/missing_smiles_Methanol.npy --startonly --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/Methanol_starting_coordinates/ --cachelocation additional_external_caches/CACHE_Methanol_external_test_set/ --oneonly -sl Calculated_data/Externalt_test_set_additional_Methanol/')
sbatch --dependency=afterany:$job1 --array=0-0 -n 4 --time=24:00:00 --tmp=5000 --mem-per-cpu=4000 --gpus=1 -o Calculated_data/Externalt_test_set_additional_Methanol/slurm_log/run_generation_Methanol_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "CO" -r 161312 -f generation_smiles/missing_testset_smiles/missing_smiles_Methanol.npy -nf 1 --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/Methanol_starting_coordinates/ -sl Calculated_data/Externalt_test_set_additional_Methanol/ --cachelocation additional_external_caches/CACHE_Methanol_external_test_set/ --oneonly'

mkdir -p /cluster/project/igc/kpaul/Additional_external_test_set/DMSO_starting_coordinates
mkdir -p additional_external_caches/CACHE_DMSO_external_test_set/
mkdir -p Calculated_data/Externalt_test_set_additional_DMSO
job2=$(sbatch --parsable --array=0-0 -n 4 --time=24:00:00 --tmp=1000 --mem-per-cpu=4000 -o Calculated_data/slurm_log/run_generation_external_test_additional_DMSO_starting_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "CS(=O)C" -r 161313 -f generation_smiles/missing_testset_smiles/missing_smiles_DMSO.npy --startonly --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/DMSO_starting_coordinates/ --cachelocation additional_external_caches/CACHE_DMSO_external_test_set/ --oneonly -sl Calculated_data/Externalt_test_set_additional_DMSO/')
sbatch --dependency=afterany:$job2 --array=0-0 -n 4 --time=24:00:00 --tmp=5000 --mem-per-cpu=4000 --gpus=1 -o Calculated_data/Externalt_test_set_additional_DMSO/slurm_log/run_generation_DMSO_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "CS(=O)C" -r 161313 -f generation_smiles/missing_testset_smiles/missing_smiles_DMSO.npy -nf 1 --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/DMSO_starting_coordinates/ -sl Calculated_data/Externalt_test_set_additional_DMSO/ --cachelocation additional_external_caches/CACHE_DMSO_external_test_set/ --oneonly'

mkdir -p /cluster/project/igc/kpaul/Additional_external_test_set/DMPU_starting_coordinates
mkdir -p additional_external_caches/CACHE_DMPU_external_test_set/
mkdir -p Calculated_data/Externalt_test_set_additional_DMPU
job3=$(sbatch --parsable --array=0-0 -n 4 --time=24:00:00 --tmp=1000 --mem-per-cpu=4000 -o Calculated_data/slurm_log/run_generation_external_test_additional_DMPU_starting_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "O=C1N(C)CCCN1C" -r 161314 -f generation_smiles/missing_testset_smiles/missing_smiles_DMPU.npy --startonly --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/DMPU_starting_coordinates/ --cachelocation additional_external_caches/CACHE_DMPU_external_test_set/ --oneonly -sl Calculated_data/Externalt_test_set_additional_DMPU/')
sbatch --dependency=afterany:$job3 --array=0-0 -n 4 --time=24:00:00 --tmp=5000 --mem-per-cpu=4000 --gpus=1 -o Calculated_data/Externalt_test_set_additional_DMPU/slurm_log/run_generation_DMPU_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "O=C1N(C)CCCN1C" -r 161314 -f generation_smiles/missing_testset_smiles/missing_smiles_DMPU.npy -nf 1 --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/DMPU_starting_coordinates/ -sl Calculated_data/Externalt_test_set_additional_DMPU/ --cachelocation additional_external_caches/CACHE_DMPU_external_test_set/ --oneonly'

mkdir -p /cluster/project/igc/kpaul/Additional_external_test_set/Diethylether_starting_coordinates
mkdir -p additional_external_caches/CACHE_Diethylether_external_test_set/
mkdir -p Calculated_data/Externalt_test_set_additional_Diethylether
job4=$(sbatch --parsable --array=0-0 -n 4 --time=24:00:00 --tmp=1000 --mem-per-cpu=4000 -o Calculated_data/slurm_log/run_generation_external_test_additional_Diethylether_starting_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "CCOCC" -r 161315 -f generation_smiles/missing_testset_smiles/missing_smiles_Diethylether.npy --startonly --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/Diethylether_starting_coordinates/ --cachelocation additional_external_caches/CACHE_Diethylether_external_test_set/ --oneonly -sl Calculated_data/Externalt_test_set_additional_Diethylether/')
sbatch --dependency=afterany:$job4 --array=0-0 -n 4 --time=24:00:00 --tmp=5000 --mem-per-cpu=4000 --gpus=1 -o Calculated_data/Externalt_test_set_additional_Diethylether/slurm_log/run_generation_Diethylether_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "CCOCC" -r 161315 -f generation_smiles/missing_testset_smiles/missing_smiles_Diethylether.npy -nf 1 --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/Diethylether_starting_coordinates/ -sl Calculated_data/Externalt_test_set_additional_Diethylether/ --cachelocation additional_external_caches/CACHE_Diethylether_external_test_set/ --oneonly'

mkdir -p /cluster/project/igc/kpaul/Additional_external_test_set/Ethanol_starting_coordinates
mkdir -p additional_external_caches/CACHE_Ethanol_external_test_set/
mkdir -p Calculated_data/Externalt_test_set_additional_Ethanol
job5=$(sbatch --parsable --array=0-0 -n 4 --time=24:00:00 --tmp=1000 --mem-per-cpu=4000 -o Calculated_data/slurm_log/run_generation_external_test_additional_Ethanol_starting_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "OCC" -r 161316 -f generation_smiles/missing_testset_smiles/missing_smiles_Ethanol.npy --startonly --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/Ethanol_starting_coordinates/ --cachelocation additional_external_caches/CACHE_Ethanol_external_test_set/ --oneonly -sl Calculated_data/Externalt_test_set_additional_Ethanol/')
sbatch --dependency=afterany:$job5 --array=0-0 -n 4 --time=24:00:00 --tmp=5000 --mem-per-cpu=4000 --gpus=1 -o Calculated_data/Externalt_test_set_additional_Ethanol/slurm_log/run_generation_Ethanol_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "OCC" -r 161316 -f generation_smiles/missing_testset_smiles/missing_smiles_Ethanol.npy -nf 1 --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/Ethanol_starting_coordinates/ -sl Calculated_data/Externalt_test_set_additional_Ethanol/ --cachelocation additional_external_caches/CACHE_Ethanol_external_test_set/ --oneonly'

mkdir -p /cluster/project/igc/kpaul/Additional_external_test_set/DMF_starting_coordinates
mkdir -p additional_external_caches/CACHE_DMF_external_test_set/
mkdir -p Calculated_data/Externalt_test_set_additional_DMF
job6=$(sbatch --parsable --array=0-0 -n 4 --time=24:00:00 --tmp=1000 --mem-per-cpu=4000 -o Calculated_data/slurm_log/run_generation_external_test_additional_DMF_starting_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "CN(C)C=O" -r 161317 -f generation_smiles/missing_testset_smiles/missing_smiles_DMF.npy --startonly --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/DMF_starting_coordinates/ --cachelocation additional_external_caches/CACHE_DMF_external_test_set/ --oneonly -sl Calculated_data/Externalt_test_set_additional_DMF/')
sbatch --dependency=afterany:$job6 --array=0-0 -n 4 --time=24:00:00 --tmp=5000 --mem-per-cpu=4000 --gpus=1 -o Calculated_data/Externalt_test_set_additional_DMF/slurm_log/run_generation_DMF_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "CN(C)C=O" -r 161317 -f generation_smiles/missing_testset_smiles/missing_smiles_DMF.npy -nf 1 --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/DMF_starting_coordinates/ -sl Calculated_data/Externalt_test_set_additional_DMF/ --cachelocation additional_external_caches/CACHE_DMF_external_test_set/ --oneonly'

mkdir -p /cluster/project/igc/kpaul/Additional_external_test_set/DCM_starting_coordinates
mkdir -p additional_external_caches/CACHE_DCM_external_test_set/
mkdir -p Calculated_data/Externalt_test_set_additional_DCM
job7=$(sbatch --parsable --array=0-0 -n 4 --time=24:00:00 --tmp=1000 --mem-per-cpu=4000 -o Calculated_data/slurm_log/run_generation_external_test_additional_DCM_starting_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "ClCCl" -r 161318 -f generation_smiles/missing_testset_smiles/missing_smiles_DCM.npy --startonly --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/DCM_starting_coordinates/ --cachelocation additional_external_caches/CACHE_DCM_external_test_set/ --oneonly -sl Calculated_data/Externalt_test_set_additional_DCM/')
sbatch --dependency=afterany:$job7 --array=0-0 -n 4 --time=24:00:00 --tmp=5000 --mem-per-cpu=4000 --gpus=1 -o Calculated_data/Externalt_test_set_additional_DCM/slurm_log/run_generation_DCM_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "ClCCl" -r 161318 -f generation_smiles/missing_testset_smiles/missing_smiles_DCM.npy -nf 1 --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/DCM_starting_coordinates/ -sl Calculated_data/Externalt_test_set_additional_DCM/ --cachelocation additional_external_caches/CACHE_DCM_external_test_set/ --oneonly'

mkdir -p /cluster/project/igc/kpaul/Additional_external_test_set/Toluol_starting_coordinates
mkdir -p additional_external_caches/CACHE_Toluol_external_test_set/
mkdir -p Calculated_data/Externalt_test_set_additional_Toluol
job8=$(sbatch --parsable --array=0-0 -n 4 --time=24:00:00 --tmp=1000 --mem-per-cpu=4000 -o Calculated_data/slurm_log/run_generation_external_test_additional_Toluol_starting_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "Cc1ccccc1" -r 161319 -f generation_smiles/missing_testset_smiles/missing_smiles_Toluol.npy --startonly --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/Toluol_starting_coordinates/ --cachelocation additional_external_caches/CACHE_Toluol_external_test_set/ --oneonly -sl Calculated_data/Externalt_test_set_additional_Toluol/')
sbatch --dependency=afterany:$job8 --array=0-0 -n 4 --time=24:00:00 --tmp=5000 --mem-per-cpu=4000 --gpus=1 -o Calculated_data/Externalt_test_set_additional_Toluol/slurm_log/run_generation_Toluol_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "Cc1ccccc1" -r 161319 -f generation_smiles/missing_testset_smiles/missing_smiles_Toluol.npy -nf 1 --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/Toluol_starting_coordinates/ -sl Calculated_data/Externalt_test_set_additional_Toluol/ --cachelocation additional_external_caches/CACHE_Toluol_external_test_set/ --oneonly'

mkdir -p /cluster/project/igc/kpaul/Additional_external_test_set/Benzol_starting_coordinates
mkdir -p additional_external_caches/CACHE_Benzol_external_test_set/
mkdir -p Calculated_data/Externalt_test_set_additional_Benzol
job9=$(sbatch --parsable --array=0-0 -n 4 --time=24:00:00 --tmp=1000 --mem-per-cpu=4000 -o Calculated_data/slurm_log/run_generation_external_test_additional_Benzol_starting_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "c1ccccc1" -r 161320 -f generation_smiles/missing_testset_smiles/missing_smiles_Benzol.npy --startonly --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/Benzol_starting_coordinates/ --cachelocation additional_external_caches/CACHE_Benzol_external_test_set/ --oneonly -sl Calculated_data/Externalt_test_set_additional_Benzol/')
sbatch --dependency=afterany:$job9 --array=0-0 -n 4 --time=24:00:00 --tmp=5000 --mem-per-cpu=4000 --gpus=1 -o Calculated_data/Externalt_test_set_additional_Benzol/slurm_log/run_generation_Benzol_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "c1ccccc1" -r 161320 -f generation_smiles/missing_testset_smiles/missing_smiles_Benzol.npy -nf 1 --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/Benzol_starting_coordinates/ -sl Calculated_data/Externalt_test_set_additional_Benzol/ --cachelocation additional_external_caches/CACHE_Benzol_external_test_set/ --oneonly'

mkdir -p /cluster/project/igc/kpaul/Additional_external_test_set/Hexan_starting_coordinates
mkdir -p additional_external_caches/CACHE_Hexan_external_test_set/
mkdir -p Calculated_data/Externalt_test_set_additional_Hexan
job10=$(sbatch --parsable --array=0-0 -n 4 --time=24:00:00 --tmp=1000 --mem-per-cpu=4000 -o Calculated_data/slurm_log/run_generation_external_test_additional_Hexan_starting_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "CCCCCC" -r 161321 -f generation_smiles/missing_testset_smiles/missing_smiles_Hexan.npy --startonly --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/Hexan_starting_coordinates/ --cachelocation additional_external_caches/CACHE_Hexan_external_test_set/ --oneonly -sl Calculated_data/Externalt_test_set_additional_Hexan/')
sbatch --dependency=afterany:$job10 --array=0-0 -n 4 --time=24:00:00 --tmp=5000 --mem-per-cpu=4000 --gpus=1 -o Calculated_data/Externalt_test_set_additional_Hexan/slurm_log/run_generation_Hexan_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "CCCCCC" -r 161321 -f generation_smiles/missing_testset_smiles/missing_smiles_Hexan.npy -nf 1 --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/Hexan_starting_coordinates/ -sl Calculated_data/Externalt_test_set_additional_Hexan/ --cachelocation additional_external_caches/CACHE_Hexan_external_test_set/ --oneonly'

mkdir -p /cluster/project/igc/kpaul/Additional_external_test_set/acetonitrile_starting_coordinates
mkdir -p additional_external_caches/CACHE_acetonitrile_external_test_set/
mkdir -p Calculated_data/Externalt_test_set_additional_acetonitrile
job11=$(sbatch --parsable --array=0-0 -n 4 --time=24:00:00 --tmp=1000 --mem-per-cpu=4000 -o Calculated_data/slurm_log/run_generation_external_test_additional_acetonitrile_starting_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "CC#N" -r 161322 -f generation_smiles/missing_testset_smiles/missing_smiles_acetonitrile.npy --startonly --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/acetonitrile_starting_coordinates/ --cachelocation additional_external_caches/CACHE_acetonitrile_external_test_set/ --oneonly -sl Calculated_data/Externalt_test_set_additional_acetonitrile/')
sbatch --dependency=afterany:$job11 --array=0-0 -n 4 --time=24:00:00 --tmp=5000 --mem-per-cpu=4000 --gpus=1 -o Calculated_data/Externalt_test_set_additional_acetonitrile/slurm_log/run_generation_acetonitrile_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "CC#N" -r 161322 -f generation_smiles/missing_testset_smiles/missing_smiles_acetonitrile.npy -nf 1 --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/acetonitrile_starting_coordinates/ -sl Calculated_data/Externalt_test_set_additional_acetonitrile/ --cachelocation additional_external_caches/CACHE_acetonitrile_external_test_set/ --oneonly'

mkdir -p /cluster/project/igc/kpaul/Additional_external_test_set/acetone_starting_coordinates
mkdir -p additional_external_caches/CACHE_acetone_external_test_set/
mkdir -p Calculated_data/Externalt_test_set_additional_acetone
job12=$(sbatch --parsable --array=0-1 -n 4 --time=24:00:00 --tmp=1000 --mem-per-cpu=4000 -o Calculated_data/slurm_log/run_generation_external_test_additional_acetone_starting_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "CC(=O)C" -r 161323 -f generation_smiles/missing_testset_smiles/missing_smiles_acetone.npy --startonly --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/acetone_starting_coordinates/ --cachelocation additional_external_caches/CACHE_acetone_external_test_set/ --oneonly -sl Calculated_data/Externalt_test_set_additional_acetone/')
sbatch --dependency=afterany:$job12 --array=0-1 -n 4 --time=24:00:00 --tmp=5000 --mem-per-cpu=4000 --gpus=1 -o Calculated_data/Externalt_test_set_additional_acetone/slurm_log/run_generation_acetone_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "CC(=O)C" -r 161323 -f generation_smiles/missing_testset_smiles/missing_smiles_acetone.npy -nf 1 --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/acetone_starting_coordinates/ -sl Calculated_data/Externalt_test_set_additional_acetone/ --cachelocation additional_external_caches/CACHE_acetone_external_test_set/ --oneonly'

mkdir -p /cluster/project/igc/kpaul/Additional_external_test_set/aceticacid_starting_coordinates
mkdir -p additional_external_caches/CACHE_aceticacid_external_test_set/
mkdir -p Calculated_data/Externalt_test_set_additional_aceticacid
job13=$(sbatch --parsable --array=0-1 -n 4 --time=24:00:00 --tmp=1000 --mem-per-cpu=4000 -o Calculated_data/slurm_log/run_generation_external_test_additional_aceticacid_starting_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "CC(O)=O" -r 161324 -f generation_smiles/missing_testset_smiles/missing_smiles_aceticacid.npy --startonly --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/aceticacid_starting_coordinates/ --cachelocation additional_external_caches/CACHE_aceticacid_external_test_set/ --oneonly -sl Calculated_data/Externalt_test_set_additional_aceticacid/')
sbatch --dependency=afterany:$job13 --array=0-1 -n 4 --time=24:00:00 --tmp=5000 --mem-per-cpu=4000 --gpus=1 -o Calculated_data/Externalt_test_set_additional_aceticacid/slurm_log/run_generation_aceticacid_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "CC(O)=O" -r 161324 -f generation_smiles/missing_testset_smiles/missing_smiles_aceticacid.npy -nf 1 --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/aceticacid_starting_coordinates/ -sl Calculated_data/Externalt_test_set_additional_aceticacid/ --cachelocation additional_external_caches/CACHE_aceticacid_external_test_set/ --oneonly'

mkdir -p /cluster/project/igc/kpaul/Additional_external_test_set/14dioxane_starting_coordinates
mkdir -p additional_external_caches/CACHE_14dioxane_external_test_set/
mkdir -p Calculated_data/Externalt_test_set_additional_14dioxane
job14=$(sbatch --parsable --array=0-1 -n 4 --time=24:00:00 --tmp=1000 --mem-per-cpu=4000 -o Calculated_data/slurm_log/run_generation_external_test_additional_14dioxane_starting_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "O1CCOCC1" -r 161325 -f generation_smiles/missing_testset_smiles/missing_smiles_14dioxane.npy --startonly --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/14dioxane_starting_coordinates/ --cachelocation additional_external_caches/CACHE_14dioxane_external_test_set/ --oneonly -sl Calculated_data/Externalt_test_set_additional_14dioxane/')
sbatch --dependency=afterany:$job14 --array=0-1 -n 4 --time=24:00:00 --tmp=5000 --mem-per-cpu=4000 --gpus=1 -o Calculated_data/Externalt_test_set_additional_14dioxane/slurm_log/run_generation_14dioxane_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "O1CCOCC1" -r 161325 -f generation_smiles/missing_testset_smiles/missing_smiles_14dioxane.npy -nf 1 --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/14dioxane_starting_coordinates/ -sl Calculated_data/Externalt_test_set_additional_14dioxane/ --cachelocation additional_external_caches/CACHE_14dioxane_external_test_set/ --oneonly'

mkdir -p /cluster/project/igc/kpaul/Additional_external_test_set/nitrobenzol_starting_coordinates
mkdir -p additional_external_caches/CACHE_nitrobenzol_external_test_set/
mkdir -p Calculated_data/Externalt_test_set_additional_nitrobenzol
job15=$(sbatch --parsable --array=0-0 -n 4 --time=24:00:00 --tmp=1000 --mem-per-cpu=4000 -o Calculated_data/slurm_log/run_generation_external_test_additional_nitrobenzol_starting_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "c1ccc(cc1)[N+](=O)[O-]" -r 161326 -f generation_smiles/missing_testset_smiles/missing_smiles_nitrobenzol.npy --startonly --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/nitrobenzol_starting_coordinates/ --cachelocation additional_external_caches/CACHE_nitrobenzol_external_test_set/ --oneonly -sl Calculated_data/Externalt_test_set_additional_nitrobenzol/')
sbatch --dependency=afterany:$job15 --array=0-0 -n 4 --time=24:00:00 --tmp=5000 --mem-per-cpu=4000 --gpus=1 -o Calculated_data/Externalt_test_set_additional_nitrobenzol/slurm_log/run_generation_nitrobenzol_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "c1ccc(cc1)[N+](=O)[O-]" -r 161326 -f generation_smiles/missing_testset_smiles/missing_smiles_nitrobenzol.npy -nf 1 --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/nitrobenzol_starting_coordinates/ -sl Calculated_data/Externalt_test_set_additional_nitrobenzol/ --cachelocation additional_external_caches/CACHE_nitrobenzol_external_test_set/ --oneonly'

mkdir -p /cluster/project/igc/kpaul/Additional_external_test_set/HMPA_starting_coordinates
mkdir -p additional_external_caches/CACHE_HMPA_external_test_set/
mkdir -p Calculated_data/Externalt_test_set_additional_HMPA
job16=$(sbatch --parsable --array=0-0 -n 4 --time=24:00:00 --tmp=1000 --mem-per-cpu=4000 -o Calculated_data/slurm_log/run_generation_external_test_additional_HMPA_starting_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "O=P(N(C)C)(N(C)C)N(C)C" -r 161327 -f generation_smiles/missing_testset_smiles/missing_smiles_HMPA.npy --startonly --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/HMPA_starting_coordinates/ --cachelocation additional_external_caches/CACHE_HMPA_external_test_set/ --oneonly -sl Calculated_data/Externalt_test_set_additional_HMPA/')
sbatch --dependency=afterany:$job16 --array=0-0 -n 4 --time=24:00:00 --tmp=5000 --mem-per-cpu=4000 --gpus=1 -o Calculated_data/Externalt_test_set_additional_HMPA/slurm_log/run_generation_HMPA_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "O=P(N(C)C)(N(C)C)N(C)C" -r 161327 -f generation_smiles/missing_testset_smiles/missing_smiles_HMPA.npy -nf 1 --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/HMPA_starting_coordinates/ -sl Calculated_data/Externalt_test_set_additional_HMPA/ --cachelocation additional_external_caches/CACHE_HMPA_external_test_set/ --oneonly'

mkdir -p /cluster/project/igc/kpaul/Additional_external_test_set/MTBE_starting_coordinates
mkdir -p additional_external_caches/CACHE_MTBE_external_test_set/
mkdir -p Calculated_data/Externalt_test_set_additional_MTBE
job17=$(sbatch --parsable --array=0-1 -n 4 --time=24:00:00 --tmp=1000 --mem-per-cpu=4000 -o Calculated_data/slurm_log/run_generation_external_test_additional_MTBE_starting_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "O(C(C)(C)C)C" -r 161328 -f generation_smiles/missing_testset_smiles/missing_smiles_MTBE.npy --startonly --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/MTBE_starting_coordinates/ --cachelocation additional_external_caches/CACHE_MTBE_external_test_set/ --oneonly -sl Calculated_data/Externalt_test_set_additional_MTBE/')
sbatch --dependency=afterany:$job17 --array=0-1 -n 4 --time=24:00:00 --tmp=5000 --mem-per-cpu=4000 --gpus=1 -o Calculated_data/Externalt_test_set_additional_MTBE/slurm_log/run_generation_MTBE_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "O(C(C)(C)C)C" -r 161328 -f generation_smiles/missing_testset_smiles/missing_smiles_MTBE.npy -nf 1 --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/MTBE_starting_coordinates/ -sl Calculated_data/Externalt_test_set_additional_MTBE/ --cachelocation additional_external_caches/CACHE_MTBE_external_test_set/ --oneonly'

mkdir -p /cluster/project/igc/kpaul/Additional_external_test_set/IPA_starting_coordinates
mkdir -p additional_external_caches/CACHE_IPA_external_test_set/
mkdir -p Calculated_data/Externalt_test_set_additional_IPA
job18=$(sbatch --parsable --array=0-0 -n 4 --time=24:00:00 --tmp=1000 --mem-per-cpu=4000 -o Calculated_data/slurm_log/run_generation_external_test_additional_IPA_starting_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "CC(O)C" -r 161329 -f generation_smiles/missing_testset_smiles/missing_smiles_IPA.npy --startonly --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/IPA_starting_coordinates/ --cachelocation additional_external_caches/CACHE_IPA_external_test_set/ --oneonly -sl Calculated_data/Externalt_test_set_additional_IPA/')
sbatch --dependency=afterany:$job18 --array=0-0 -n 4 --time=24:00:00 --tmp=5000 --mem-per-cpu=4000 --gpus=1 -o Calculated_data/Externalt_test_set_additional_IPA/slurm_log/run_generation_IPA_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "CC(O)C" -r 161329 -f generation_smiles/missing_testset_smiles/missing_smiles_IPA.npy -nf 1 --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/IPA_starting_coordinates/ -sl Calculated_data/Externalt_test_set_additional_IPA/ --cachelocation additional_external_caches/CACHE_IPA_external_test_set/ --oneonly'

mkdir -p /cluster/project/igc/kpaul/Additional_external_test_set/Hexafluorobenzene_starting_coordinates
mkdir -p additional_external_caches/CACHE_Hexafluorobenzene_external_test_set/
mkdir -p Calculated_data/Externalt_test_set_additional_Hexafluorobenzene
job19=$(sbatch --parsable --array=0-1 -n 4 --time=24:00:00 --tmp=1000 --mem-per-cpu=4000 -o Calculated_data/slurm_log/run_generation_external_test_additional_Hexafluorobenzene_starting_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "Fc1c(F)c(F)c(F)c(F)c1F" -r 161330 -f generation_smiles/missing_testset_smiles/missing_smiles_Hexafluorobenzene.npy --startonly --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/Hexafluorobenzene_starting_coordinates/ --cachelocation additional_external_caches/CACHE_Hexafluorobenzene_external_test_set/ --oneonly -sl Calculated_data/Externalt_test_set_additional_Hexafluorobenzene/')
sbatch --dependency=afterany:$job19 --array=0-1 -n 4 --time=24:00:00 --tmp=5000 --mem-per-cpu=4000 --gpus=1 -o Calculated_data/Externalt_test_set_additional_Hexafluorobenzene/slurm_log/run_generation_Hexafluorobenzene_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "Fc1c(F)c(F)c(F)c(F)c1F" -r 161330 -f generation_smiles/missing_testset_smiles/missing_smiles_Hexafluorobenzene.npy -nf 1 --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/Hexafluorobenzene_starting_coordinates/ -sl Calculated_data/Externalt_test_set_additional_Hexafluorobenzene/ --cachelocation additional_external_caches/CACHE_Hexafluorobenzene_external_test_set/ --oneonly'

mkdir -p /cluster/project/igc/kpaul/Additional_external_test_set/pyridine_starting_coordinates
mkdir -p additional_external_caches/CACHE_pyridine_external_test_set/
mkdir -p Calculated_data/Externalt_test_set_additional_pyridine
job20=$(sbatch --parsable --array=0-1 -n 4 --time=24:00:00 --tmp=1000 --mem-per-cpu=4000 -o Calculated_data/slurm_log/run_generation_external_test_additional_pyridine_starting_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "c1ccncc1" -r 161331 -f generation_smiles/missing_testset_smiles/missing_smiles_pyridine.npy --startonly --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/pyridine_starting_coordinates/ --cachelocation additional_external_caches/CACHE_pyridine_external_test_set/ --oneonly -sl Calculated_data/Externalt_test_set_additional_pyridine/')
sbatch --dependency=afterany:$job20 --array=0-1 -n 4 --time=24:00:00 --tmp=5000 --mem-per-cpu=4000 --gpus=1 -o Calculated_data/Externalt_test_set_additional_pyridine/slurm_log/run_generation_pyridine_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "c1ccncc1" -r 161331 -f generation_smiles/missing_testset_smiles/missing_smiles_pyridine.npy -nf 1 --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/pyridine_starting_coordinates/ -sl Calculated_data/Externalt_test_set_additional_pyridine/ --cachelocation additional_external_caches/CACHE_pyridine_external_test_set/ --oneonly'

mkdir -p /cluster/project/igc/kpaul/Additional_external_test_set/THF_starting_coordinates
mkdir -p additional_external_caches/CACHE_THF_external_test_set/
mkdir -p Calculated_data/Externalt_test_set_additional_THF
job21=$(sbatch --parsable --array=0-0 -n 4 --time=24:00:00 --tmp=1000 --mem-per-cpu=4000 -o Calculated_data/slurm_log/run_generation_external_test_additional_THF_starting_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "C1CCOC1" -r 161332 -f generation_smiles/missing_testset_smiles/missing_smiles_THF.npy --startonly --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/THF_starting_coordinates/ --cachelocation additional_external_caches/CACHE_THF_external_test_set/ --oneonly -sl Calculated_data/Externalt_test_set_additional_THF/')
sbatch --dependency=afterany:$job21 --array=0-0 -n 4 --time=24:00:00 --tmp=5000 --mem-per-cpu=4000 --gpus=1 -o Calculated_data/Externalt_test_set_additional_THF/slurm_log/run_generation_THF_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "C1CCOC1" -r 161332 -f generation_smiles/missing_testset_smiles/missing_smiles_THF.npy -nf 1 --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/THF_starting_coordinates/ -sl Calculated_data/Externalt_test_set_additional_THF/ --cachelocation additional_external_caches/CACHE_THF_external_test_set/ --oneonly'

mkdir -p /cluster/project/igc/kpaul/Additional_external_test_set/Ethylacetate_starting_coordinates
mkdir -p additional_external_caches/CACHE_Ethylacetate_external_test_set/
mkdir -p Calculated_data/Externalt_test_set_additional_Ethylacetate
job22=$(sbatch --parsable --array=0-0 -n 4 --time=24:00:00 --tmp=1000 --mem-per-cpu=4000 -o Calculated_data/slurm_log/run_generation_external_test_additional_Ethylacetate_starting_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "O=C(OCC)C" -r 161333 -f generation_smiles/missing_testset_smiles/missing_smiles_Ethylacetate.npy --startonly --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/Ethylacetate_starting_coordinates/ --cachelocation additional_external_caches/CACHE_Ethylacetate_external_test_set/ --oneonly -sl Calculated_data/Externalt_test_set_additional_Ethylacetate/')
sbatch --dependency=afterany:$job22 --array=0-0 -n 4 --time=24:00:00 --tmp=5000 --mem-per-cpu=4000 --gpus=1 -o Calculated_data/Externalt_test_set_additional_Ethylacetate/slurm_log/run_generation_Ethylacetate_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "O=C(OCC)C" -r 161333 -f generation_smiles/missing_testset_smiles/missing_smiles_Ethylacetate.npy -nf 1 --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/Ethylacetate_starting_coordinates/ -sl Calculated_data/Externalt_test_set_additional_Ethylacetate/ --cachelocation additional_external_caches/CACHE_Ethylacetate_external_test_set/ --oneonly'

mkdir -p /cluster/project/igc/kpaul/Additional_external_test_set/Sulfolane_starting_coordinates
mkdir -p additional_external_caches/CACHE_Sulfolane_external_test_set/
mkdir -p Calculated_data/Externalt_test_set_additional_Sulfolane
job23=$(sbatch --parsable --array=0-0 -n 4 --time=24:00:00 --tmp=1000 --mem-per-cpu=4000 -o Calculated_data/slurm_log/run_generation_external_test_additional_Sulfolane_starting_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "C1CCS(=O)(=O)C1" -r 161334 -f generation_smiles/missing_testset_smiles/missing_smiles_Sulfolane.npy --startonly --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/Sulfolane_starting_coordinates/ --cachelocation additional_external_caches/CACHE_Sulfolane_external_test_set/ --oneonly -sl Calculated_data/Externalt_test_set_additional_Sulfolane/')
sbatch --dependency=afterany:$job23 --array=0-0 -n 4 --time=24:00:00 --tmp=5000 --mem-per-cpu=4000 --gpus=1 -o Calculated_data/Externalt_test_set_additional_Sulfolane/slurm_log/run_generation_Sulfolane_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "C1CCS(=O)(=O)C1" -r 161334 -f generation_smiles/missing_testset_smiles/missing_smiles_Sulfolane.npy -nf 1 --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/Sulfolane_starting_coordinates/ -sl Calculated_data/Externalt_test_set_additional_Sulfolane/ --cachelocation additional_external_caches/CACHE_Sulfolane_external_test_set/ --oneonly'

mkdir -p /cluster/project/igc/kpaul/Additional_external_test_set/nitromethane_starting_coordinates
mkdir -p additional_external_caches/CACHE_nitromethane_external_test_set/
mkdir -p Calculated_data/Externalt_test_set_additional_nitromethane
job24=$(sbatch --parsable --array=0-0 -n 4 --time=24:00:00 --tmp=1000 --mem-per-cpu=4000 -o Calculated_data/slurm_log/run_generation_external_test_additional_nitromethane_starting_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "C[N+](=O)[O-]" -r 161335 -f generation_smiles/missing_testset_smiles/missing_smiles_nitromethane.npy --startonly --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/nitromethane_starting_coordinates/ --cachelocation additional_external_caches/CACHE_nitromethane_external_test_set/ --oneonly -sl Calculated_data/Externalt_test_set_additional_nitromethane/')
sbatch --dependency=afterany:$job24 --array=0-0 -n 4 --time=24:00:00 --tmp=5000 --mem-per-cpu=4000 --gpus=1 -o Calculated_data/Externalt_test_set_additional_nitromethane/slurm_log/run_generation_nitromethane_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "C[N+](=O)[O-]" -r 161335 -f generation_smiles/missing_testset_smiles/missing_smiles_nitromethane.npy -nf 1 --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/nitromethane_starting_coordinates/ -sl Calculated_data/Externalt_test_set_additional_nitromethane/ --cachelocation additional_external_caches/CACHE_nitromethane_external_test_set/ --oneonly'

mkdir -p /cluster/project/igc/kpaul/Additional_external_test_set/Butylformate_starting_coordinates
mkdir -p additional_external_caches/CACHE_Butylformate_external_test_set/
mkdir -p Calculated_data/Externalt_test_set_additional_Butylformate
job25=$(sbatch --parsable --array=0-0 -n 4 --time=24:00:00 --tmp=1000 --mem-per-cpu=4000 -o Calculated_data/slurm_log/run_generation_external_test_additional_Butylformate_starting_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "CC(C)(C)OC=O" -r 161336 -f generation_smiles/missing_testset_smiles/missing_smiles_Butylformate.npy --startonly --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/Butylformate_starting_coordinates/ --cachelocation additional_external_caches/CACHE_Butylformate_external_test_set/ --oneonly -sl Calculated_data/Externalt_test_set_additional_Butylformate/')
sbatch --dependency=afterany:$job25 --array=0-0 -n 4 --time=24:00:00 --tmp=5000 --mem-per-cpu=4000 --gpus=1 -o Calculated_data/Externalt_test_set_additional_Butylformate/slurm_log/run_generation_Butylformate_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "CC(C)(C)OC=O" -r 161336 -f generation_smiles/missing_testset_smiles/missing_smiles_Butylformate.npy -nf 1 --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/Butylformate_starting_coordinates/ -sl Calculated_data/Externalt_test_set_additional_Butylformate/ --cachelocation additional_external_caches/CACHE_Butylformate_external_test_set/ --oneonly'

mkdir -p /cluster/project/igc/kpaul/Additional_external_test_set/NMP_starting_coordinates
mkdir -p additional_external_caches/CACHE_NMP_external_test_set/
mkdir -p Calculated_data/Externalt_test_set_additional_NMP
job26=$(sbatch --parsable --array=0-0 -n 4 --time=24:00:00 --tmp=1000 --mem-per-cpu=4000 -o Calculated_data/slurm_log/run_generation_external_test_additional_NMP_starting_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "CN1CCCC1=O" -r 161337 -f generation_smiles/missing_testset_smiles/missing_smiles_NMP.npy --startonly --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/NMP_starting_coordinates/ --cachelocation additional_external_caches/CACHE_NMP_external_test_set/ --oneonly -sl Calculated_data/Externalt_test_set_additional_NMP/')
sbatch --dependency=afterany:$job26 --array=0-0 -n 4 --time=24:00:00 --tmp=5000 --mem-per-cpu=4000 --gpus=1 -o Calculated_data/Externalt_test_set_additional_NMP/slurm_log/run_generation_NMP_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "CN1CCCC1=O" -r 161337 -f generation_smiles/missing_testset_smiles/missing_smiles_NMP.npy -nf 1 --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/NMP_starting_coordinates/ -sl Calculated_data/Externalt_test_set_additional_NMP/ --cachelocation additional_external_caches/CACHE_NMP_external_test_set/ --oneonly'

mkdir -p /cluster/project/igc/kpaul/Additional_external_test_set/Octanol_starting_coordinates
mkdir -p additional_external_caches/CACHE_Octanol_external_test_set/
mkdir -p Calculated_data/Externalt_test_set_additional_Octanol
job27=$(sbatch --parsable --array=0-0 -n 4 --time=24:00:00 --tmp=1000 --mem-per-cpu=4000 -o Calculated_data/slurm_log/run_generation_external_test_additional_Octanol_starting_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "CCCCCCCCO" -r 161338 -f generation_smiles/missing_testset_smiles/missing_smiles_Octanol.npy --startonly --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/Octanol_starting_coordinates/ --cachelocation additional_external_caches/CACHE_Octanol_external_test_set/ --oneonly -sl Calculated_data/Externalt_test_set_additional_Octanol/')
sbatch --dependency=afterany:$job27 --array=0-0 -n 4 --time=24:00:00 --tmp=5000 --mem-per-cpu=4000 --gpus=1 -o Calculated_data/Externalt_test_set_additional_Octanol/slurm_log/run_generation_Octanol_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "CCCCCCCCO" -r 161338 -f generation_smiles/missing_testset_smiles/missing_smiles_Octanol.npy -nf 1 --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/Octanol_starting_coordinates/ -sl Calculated_data/Externalt_test_set_additional_Octanol/ --cachelocation additional_external_caches/CACHE_Octanol_external_test_set/ --oneonly'

mkdir -p /cluster/project/igc/kpaul/Additional_external_test_set/cyclohexane_starting_coordinates
mkdir -p additional_external_caches/CACHE_cyclohexane_external_test_set/
mkdir -p Calculated_data/Externalt_test_set_additional_cyclohexane
job28=$(sbatch --parsable --array=0-1 -n 4 --time=24:00:00 --tmp=1000 --mem-per-cpu=4000 -o Calculated_data/slurm_log/run_generation_external_test_additional_cyclohexane_starting_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "C1CCCCC1" -r 161339 -f generation_smiles/missing_testset_smiles/missing_smiles_cyclohexane.npy --startonly --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/cyclohexane_starting_coordinates/ --cachelocation additional_external_caches/CACHE_cyclohexane_external_test_set/ --oneonly -sl Calculated_data/Externalt_test_set_additional_cyclohexane/')
sbatch --dependency=afterany:$job28 --array=0-1 -n 4 --time=24:00:00 --tmp=5000 --mem-per-cpu=4000 --gpus=1 -o Calculated_data/Externalt_test_set_additional_cyclohexane/slurm_log/run_generation_cyclohexane_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "C1CCCCC1" -r 161339 -f generation_smiles/missing_testset_smiles/missing_smiles_cyclohexane.npy -nf 1 --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/cyclohexane_starting_coordinates/ -sl Calculated_data/Externalt_test_set_additional_cyclohexane/ --cachelocation additional_external_caches/CACHE_cyclohexane_external_test_set/ --oneonly'

mkdir -p /cluster/project/igc/kpaul/Additional_external_test_set/glycerin_starting_coordinates
mkdir -p additional_external_caches/CACHE_glycerin_external_test_set/
mkdir -p Calculated_data/Externalt_test_set_additional_glycerin
job29=$(sbatch --parsable --array=0-0 -n 4 --time=24:00:00 --tmp=1000 --mem-per-cpu=4000 -o Calculated_data/slurm_log/run_generation_external_test_additional_glycerin_starting_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "OCC(O)CO" -r 161340 -f generation_smiles/missing_testset_smiles/missing_smiles_glycerin.npy --startonly --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/glycerin_starting_coordinates/ --cachelocation additional_external_caches/CACHE_glycerin_external_test_set/ --oneonly -sl Calculated_data/Externalt_test_set_additional_glycerin/')
sbatch --dependency=afterany:$job29 --array=0-0 -n 4 --time=24:00:00 --tmp=5000 --mem-per-cpu=4000 --gpus=1 -o Calculated_data/Externalt_test_set_additional_glycerin/slurm_log/run_generation_glycerin_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "OCC(O)CO" -r 161340 -f generation_smiles/missing_testset_smiles/missing_smiles_glycerin.npy -nf 1 --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/glycerin_starting_coordinates/ -sl Calculated_data/Externalt_test_set_additional_glycerin/ --cachelocation additional_external_caches/CACHE_glycerin_external_test_set/ --oneonly'

mkdir -p /cluster/project/igc/kpaul/Additional_external_test_set/carbontetrachloride_starting_coordinates
mkdir -p additional_external_caches/CACHE_carbontetrachloride_external_test_set/
mkdir -p Calculated_data/Externalt_test_set_additional_carbontetrachloride
job30=$(sbatch --parsable --array=0-0 -n 4 --time=24:00:00 --tmp=1000 --mem-per-cpu=4000 -o Calculated_data/slurm_log/run_generation_external_test_additional_carbontetrachloride_starting_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "ClC(Cl)(Cl)Cl" -r 161341 -f generation_smiles/missing_testset_smiles/missing_smiles_carbontetrachloride.npy --startonly --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/carbontetrachloride_starting_coordinates/ --cachelocation additional_external_caches/CACHE_carbontetrachloride_external_test_set/ --oneonly -sl Calculated_data/Externalt_test_set_additional_carbontetrachloride/')
sbatch --dependency=afterany:$job30 --array=0-0 -n 4 --time=24:00:00 --tmp=5000 --mem-per-cpu=4000 --gpus=1 -o Calculated_data/Externalt_test_set_additional_carbontetrachloride/slurm_log/run_generation_carbontetrachloride_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "ClC(Cl)(Cl)Cl" -r 161341 -f generation_smiles/missing_testset_smiles/missing_smiles_carbontetrachloride.npy -nf 1 --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/carbontetrachloride_starting_coordinates/ -sl Calculated_data/Externalt_test_set_additional_carbontetrachloride/ --cachelocation additional_external_caches/CACHE_carbontetrachloride_external_test_set/ --oneonly'

mkdir -p /cluster/project/igc/kpaul/Additional_external_test_set/DME_starting_coordinates
mkdir -p additional_external_caches/CACHE_DME_external_test_set/
mkdir -p Calculated_data/Externalt_test_set_additional_DME
job31=$(sbatch --parsable --array=0-12 -n 4 --time=24:00:00 --tmp=1000 --mem-per-cpu=4000 -o Calculated_data/slurm_log/run_generation_external_test_additional_DME_starting_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "COCCOC" -r 161342 -f generation_smiles/missing_testset_smiles/missing_smiles_DME.npy --startonly --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/DME_starting_coordinates/ --cachelocation additional_external_caches/CACHE_DME_external_test_set/ --oneonly -sl Calculated_data/Externalt_test_set_additional_DME/')
sbatch --dependency=afterany:$job31 --array=0-12 -n 4 --time=24:00:00 --tmp=5000 --mem-per-cpu=4000 --gpus=1 -o Calculated_data/Externalt_test_set_additional_DME/slurm_log/run_generation_DME_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "COCCOC" -r 161342 -f generation_smiles/missing_testset_smiles/missing_smiles_DME.npy -nf 1 --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/DME_starting_coordinates/ -sl Calculated_data/Externalt_test_set_additional_DME/ --cachelocation additional_external_caches/CACHE_DME_external_test_set/ --oneonly'

mkdir -p /cluster/project/igc/kpaul/Additional_external_test_set/2Nitropropane_starting_coordinates
mkdir -p additional_external_caches/CACHE_2Nitropropane_external_test_set/
mkdir -p Calculated_data/Externalt_test_set_additional_2Nitropropane
job32=$(sbatch --parsable --array=0-2 -n 4 --time=24:00:00 --tmp=1000 --mem-per-cpu=4000 -o Calculated_data/slurm_log/run_generation_external_test_additional_2Nitropropane_starting_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "CC(C)[N+](=O)[O-]" -r 161343 -f generation_smiles/missing_testset_smiles/missing_smiles_2Nitropropane.npy --startonly --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/2Nitropropane_starting_coordinates/ --cachelocation additional_external_caches/CACHE_2Nitropropane_external_test_set/ --oneonly -sl Calculated_data/Externalt_test_set_additional_2Nitropropane/')
sbatch --dependency=afterany:$job32 --array=0-2 -n 4 --time=24:00:00 --tmp=5000 --mem-per-cpu=4000 --gpus=1 -o Calculated_data/Externalt_test_set_additional_2Nitropropane/slurm_log/run_generation_2Nitropropane_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "CC(C)[N+](=O)[O-]" -r 161343 -f generation_smiles/missing_testset_smiles/missing_smiles_2Nitropropane.npy -nf 1 --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/2Nitropropane_starting_coordinates/ -sl Calculated_data/Externalt_test_set_additional_2Nitropropane/ --cachelocation additional_external_caches/CACHE_2Nitropropane_external_test_set/ --oneonly'

mkdir -p /cluster/project/igc/kpaul/Additional_external_test_set/Trifluorotoluene_starting_coordinates
mkdir -p additional_external_caches/CACHE_Trifluorotoluene_external_test_set/
mkdir -p Calculated_data/Externalt_test_set_additional_Trifluorotoluene
job33=$(sbatch --parsable --array=0-1 -n 4 --time=24:00:00 --tmp=1000 --mem-per-cpu=4000 -o Calculated_data/slurm_log/run_generation_external_test_additional_Trifluorotoluene_starting_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "C1=CC=C(C=C1)C(F)(F)F" -r 161344 -f generation_smiles/missing_testset_smiles/missing_smiles_Trifluorotoluene.npy --startonly --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/Trifluorotoluene_starting_coordinates/ --cachelocation additional_external_caches/CACHE_Trifluorotoluene_external_test_set/ --oneonly -sl Calculated_data/Externalt_test_set_additional_Trifluorotoluene/')
sbatch --dependency=afterany:$job33 --array=0-1 -n 4 --time=24:00:00 --tmp=5000 --mem-per-cpu=4000 --gpus=1 -o Calculated_data/Externalt_test_set_additional_Trifluorotoluene/slurm_log/run_generation_Trifluorotoluene_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "C1=CC=C(C=C1)C(F)(F)F" -r 161344 -f generation_smiles/missing_testset_smiles/missing_smiles_Trifluorotoluene.npy -nf 1 --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/Trifluorotoluene_starting_coordinates/ -sl Calculated_data/Externalt_test_set_additional_Trifluorotoluene/ --cachelocation additional_external_caches/CACHE_Trifluorotoluene_external_test_set/ --oneonly'

mkdir -p /cluster/project/igc/kpaul/Additional_external_test_set/hexafluroacetone_starting_coordinates
mkdir -p additional_external_caches/CACHE_hexafluroacetone_external_test_set/
mkdir -p Calculated_data/Externalt_test_set_additional_hexafluroacetone
job34=$(sbatch --parsable --array=0-0 -n 4 --time=24:00:00 --tmp=1000 --mem-per-cpu=4000 -o Calculated_data/slurm_log/run_generation_external_test_additional_hexafluroacetone_starting_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "FC(F)(F)C(=O)C(F)(F)F" -r 161345 -f generation_smiles/missing_testset_smiles/missing_smiles_hexafluroacetone.npy --startonly --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/hexafluroacetone_starting_coordinates/ --cachelocation additional_external_caches/CACHE_hexafluroacetone_external_test_set/ --oneonly -sl Calculated_data/Externalt_test_set_additional_hexafluroacetone/')
sbatch --dependency=afterany:$job34 --array=0-0 -n 4 --time=24:00:00 --tmp=5000 --mem-per-cpu=4000 --gpus=1 -o Calculated_data/Externalt_test_set_additional_hexafluroacetone/slurm_log/run_generation_hexafluroacetone_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "FC(F)(F)C(=O)C(F)(F)F" -r 161345 -f generation_smiles/missing_testset_smiles/missing_smiles_hexafluroacetone.npy -nf 1 --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/hexafluroacetone_starting_coordinates/ -sl Calculated_data/Externalt_test_set_additional_hexafluroacetone/ --cachelocation additional_external_caches/CACHE_hexafluroacetone_external_test_set/ --oneonly'

mkdir -p /cluster/project/igc/kpaul/Additional_external_test_set/Propionitrile_starting_coordinates
mkdir -p additional_external_caches/CACHE_Propionitrile_external_test_set/
mkdir -p Calculated_data/Externalt_test_set_additional_Propionitrile
job35=$(sbatch --parsable --array=0-0 -n 4 --time=24:00:00 --tmp=1000 --mem-per-cpu=4000 -o Calculated_data/slurm_log/run_generation_external_test_additional_Propionitrile_starting_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "CCC#N" -r 161346 -f generation_smiles/missing_testset_smiles/missing_smiles_Propionitrile.npy --startonly --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/Propionitrile_starting_coordinates/ --cachelocation additional_external_caches/CACHE_Propionitrile_external_test_set/ --oneonly -sl Calculated_data/Externalt_test_set_additional_Propionitrile/')
sbatch --dependency=afterany:$job35 --array=0-0 -n 4 --time=24:00:00 --tmp=5000 --mem-per-cpu=4000 --gpus=1 -o Calculated_data/Externalt_test_set_additional_Propionitrile/slurm_log/run_generation_Propionitrile_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "CCC#N" -r 161346 -f generation_smiles/missing_testset_smiles/missing_smiles_Propionitrile.npy -nf 1 --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/Propionitrile_starting_coordinates/ -sl Calculated_data/Externalt_test_set_additional_Propionitrile/ --cachelocation additional_external_caches/CACHE_Propionitrile_external_test_set/ --oneonly'

mkdir -p /cluster/project/igc/kpaul/Additional_external_test_set/Benzonitrile_starting_coordinates
mkdir -p additional_external_caches/CACHE_Benzonitrile_external_test_set/
mkdir -p Calculated_data/Externalt_test_set_additional_Benzonitrile
job36=$(sbatch --parsable --array=0-0 -n 4 --time=24:00:00 --tmp=1000 --mem-per-cpu=4000 -o Calculated_data/slurm_log/run_generation_external_test_additional_Benzonitrile_starting_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "N#Cc1ccccc1" -r 161347 -f generation_smiles/missing_testset_smiles/missing_smiles_Benzonitrile.npy --startonly --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/Benzonitrile_starting_coordinates/ --cachelocation additional_external_caches/CACHE_Benzonitrile_external_test_set/ --oneonly -sl Calculated_data/Externalt_test_set_additional_Benzonitrile/')
sbatch --dependency=afterany:$job36 --array=0-0 -n 4 --time=24:00:00 --tmp=5000 --mem-per-cpu=4000 --gpus=1 -o Calculated_data/Externalt_test_set_additional_Benzonitrile/slurm_log/run_generation_Benzonitrile_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "N#Cc1ccccc1" -r 161347 -f generation_smiles/missing_testset_smiles/missing_smiles_Benzonitrile.npy -nf 1 --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/Benzonitrile_starting_coordinates/ -sl Calculated_data/Externalt_test_set_additional_Benzonitrile/ --cachelocation additional_external_caches/CACHE_Benzonitrile_external_test_set/ --oneonly'

mkdir -p /cluster/project/igc/kpaul/Additional_external_test_set/oxylol_starting_coordinates
mkdir -p additional_external_caches/CACHE_oxylol_external_test_set/
mkdir -p Calculated_data/Externalt_test_set_additional_oxylol
job37=$(sbatch --parsable --array=0-1 -n 4 --time=24:00:00 --tmp=1000 --mem-per-cpu=4000 -o Calculated_data/slurm_log/run_generation_external_test_additional_oxylol_starting_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "CC1=C(C)C=CC=C1" -r 161348 -f generation_smiles/missing_testset_smiles/missing_smiles_oxylol.npy --startonly --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/oxylol_starting_coordinates/ --cachelocation additional_external_caches/CACHE_oxylol_external_test_set/ --oneonly -sl Calculated_data/Externalt_test_set_additional_oxylol/')
sbatch --dependency=afterany:$job37 --array=0-1 -n 4 --time=24:00:00 --tmp=5000 --mem-per-cpu=4000 --gpus=1 -o Calculated_data/Externalt_test_set_additional_oxylol/slurm_log/run_generation_oxylol_%A_%a.out --wrap='python run_training_set_generation.py -i $SLURM_ARRAY_TASK_ID -n 50 -s "CC1=C(C)C=CC=C1" -r 161348 -f generation_smiles/missing_testset_smiles/missing_smiles_oxylol.npy -nf 1 --starttrajloc /cluster/project/igc/kpaul/Additional_external_test_set/oxylol_starting_coordinates/ -sl Calculated_data/Externalt_test_set_additional_oxylol/ --cachelocation additional_external_caches/CACHE_oxylol_external_test_set/ --oneonly'
